config/routes.rb
Rails.application.routes.draw do
  resources :enrollments do
    get :my_students, on: :collection
  end
  devise_for :users
  resources :courses do
    get :learning, :pending_review, :teaching, :unapproved, on: :collection
    member do
      get :analytics
      patch :approve
      patch :unapprove
    end
    resources :lessons do
      put :sort
    end
    resources :enrollments, only: [:new, :create]
  end
  resources :users, only: [:index, :edit, :show, :update]

  namespace :charts do
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'money_makers'
  end
  
  get 'home/index'
  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course, counter_cache: true
  #Course.find_each { |course| Course.reset_counters(course.id, :lessons) }  
  has_many :user_lessons, dependent: :destroy
  validates :title, length: { maximum: 70 }
  validates_uniqueness_of :title, scope: :course_id

  has_rich_text :instruction
  has_one_attached :video
  has_one_attached :video_thumbnail
  # validates :video,
  #   content_type: ['video/mp4'], 
  #   size: { less_than: 50.megabytes , message: 'size should be under 50 megabytes' }
  # validates :video_thumbnail,
  #   content_type: ['image/png', 'image/jpg', 'image/jpeg'], 
  #   size: { less_than: 500.kilobytes , message: 'size should be under 500 kilobytes.' }

  extend FriendlyId
  friendly_id :title, use: :slugged

  include PublicActivity::Model
  tracked owner: Proc.new{ |controller, model| controller.current_user }

  include RankedModel
  ranks :row_order, :with_same => :course_id

  def to_s
    title
  end

  def prev
    course.lessons.where("row_order < ?", row_order).order(:row_order).last
  end

  def next
    course.lessons.where("row_order > ?", row_order).order(:row_order).first
  end

  def viewed(user)
    self.user_lessons.where(user: user).present?
    #self.user_lessons.where(user_id: [user.id], lesson_id: [self.id]).empty?
  end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  def sort
    @course = Course.friendly.find(params[:course_id])
    lesson = Lesson.friendly.find(params[:lesson_id])
    authorize lesson, :edit?
    lesson.update(lesson_params)
    render body: nil
  end

  def index
    @lessons = Lesson.all
  end

  def show
    authorize @lesson
    current_user.view_lesson(@lesson)
    @lessons = @course.lessons.rank(:row_order)
  end

  def new
    @lesson = Lesson.new
    @course = Course.friendly.find(params[:course_id])
  end

  def edit
    authorize @lesson
  end

  def create
    @lesson = Lesson.new(lesson_params)
    @course = Course.friendly.find(params[:course_id])
    @lesson.course_id = @course.id
    authorize @lesson
    respond_to do |format|
      if @lesson.save
        format.html { redirect_to course_lesson_path(@course, @lesson), notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @lesson
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to course_lesson_path(@course, @lesson), notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @lesson
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to course_path(@course), notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_lesson
      @course = Course.friendly.find(params[:course_id])
      @lesson = Lesson.friendly.find(params[:id])
    end

    def lesson_params
      params.require(:lesson).permit(:title, :instruction, :row_order_position, :video, :video_thumbnail)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.haml
= simple_form_for([@course, @lesson]) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title, input_html: { autocomplete: 'off' }
    = f.label :instruction
    = f.rich_text_area :instruction
    %small= f.error :content, class: 'text-danger'
    /= f.association :course
    -# = f.input :course_id, input_html: {value: @lesson.course_id || params[:course_id]}, as: :hidden
    = f.input :video
    = f.input :video_thumbnail

  .form-actions
    = f.button :submit

app/views/lessons/_lesson.html.haml
.card
  .card-header
    - if lesson.viewed(current_user) == true
      .text-success.far.fa-check-square
      /VIEWED
    - else
      .text-danger.far.fa-check-square
      /NOT VIEWED
    = link_to course_lesson_path(@course, lesson) do
      %b
    - if @lesson.video.attached?
      - if @lesson.video_thumbnail.attached?
        %video(controls="true" poster="#{url_for @lesson.video_thumbnail}" width="100%" preload="metadata")
          %source{src: rails_blob_url(@lesson.video), type:"#{@lesson.video.content_type}"}
      - else
        %video(controls="true" width="100%" preload="metadata")
          %source{src: rails_blob_url(@lesson.video), type:"#{@lesson.video.content_type}"}
      = lesson.title
  - if policy(lesson).show?
    .card-body
      = lesson.instruction
  - if policy(lesson).edit?
    .card-footer
      = link_to 'Edit', edit_course_lesson_path(@course, lesson), class: 'btn btn-sm btn-warning'
      = link_to 'Destroy', [@course, lesson], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'
  .card-footer
    - unless lesson.prev.nil?
      .float-left
        = link_to course_lesson_path(@course, lesson.prev), class: 'btn btn-sm btn-info' do
          .fa.fa-arrow-left
          Previous
    - unless lesson.next.nil?
      .float-right
        = link_to course_lesson_path(@course, lesson.next), class: 'btn btn-sm btn-info' do
          .fa.fa-arrow-right
          Next

app/views/lessons/_lesson_preview.html.haml
- if current_user
  - if policy(lesson).show?
    - if lesson.viewed(current_user) == true
      .text-success.fa.fa-check-square
    - else
      .text-danger.fa.fa-check-square
  - else
    .fa.fa-check-square
  = link_to course_lesson_path(@course, lesson) do 
    = lesson.row_order
    -# = lesson.row_order_rank
    = lesson.title
- else
  .fa.fa-check-square
  = link_to course_lesson_path(@course, lesson) do 
    = lesson.row_order
    -# = lesson.row_order_rank
    = lesson.title

.float-right
  - if policy(lesson).edit?
    = link_to 'Edit', edit_course_lesson_path(@course, lesson), class: 'btn btn-sm btn-warning'
    = link_to 'Destroy', [@course, lesson], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'

app/views/lessons/edit.html.haml
- content_for :title do
  Music For All 
  |
  Course
  = @course.title
  |
  Editing lesson
  = @lesson.title


= link_to 'Courses', courses_path
\/
= link_to @lesson.course.title, course_path(@lesson.course)
\/
= link_to @lesson.title, course_lesson_path(@course, @lesson)
\/
edit lesson
%p

.card
  .card-header
    %h3
      .far.fa-check-square
      Editing lesson
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Show lesson', course_lesson_path(@course, @lesson)
    \|
    = link_to 'Back to course', course_path(@lesson.course)

app/views/lessons/index.html.haml
%h1 Listing lessons

%table
  %thead
    %tr
      %th Title
      %th Instruction
      %th Course
      %th
      %th
      %th

  %tbody
    - @lessons.each do |lesson|
      %tr
        %td= lesson.title
        %td= lesson.instruction
        %td= lesson.course
        %td= link_to 'Show', lesson
        %td= link_to 'Edit', edit_lesson_path(lesson)
        %td= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Lesson', new_lesson_path

app/views/lessons/new.html.haml
- content_for :title do
  Music For All
  |
  Course
  = @course.title
  |
  New lesson

%h1 New lesson

= render 'form'

= link_to 'Back', course_path(@course)

app/views/lessons/show.html.haml
- content_for :title do
  Music For All 
  |
  Course
  = @course.title
  |
  Lesson
  = @lesson.title

= link_to 'Courses', courses_path
|
= link_to @lesson.course.title, course_path(@lesson.course)
|
= link_to @lesson.title, course_lesson_path(@course, @lesson)
%p

.row
  .col-lg-8
    = render 'lessons/lesson', lesson: @lesson
    /= @lesson.video.attached?
    /= @lesson.video_thumbnail.attached?
    -# = image_tag @lesson.video_thumbnail
    -# %video(controls="true" poster="#{url_for @lesson.video_thumbnail}" width="100%" preload="metadata")
    -#   %source{src: rails_blob_url(@lesson.video), type:"#{@lesson.video.content_type}"}

    %p
  .col-lg-4
    %ul.list-group
      %li.list-group-item
        = link_to course_path(@lesson.course) do
          .fa.fa-graduation-cap
          = @lesson.course.title
        .row
        .fa.fa-spinner
        = number_to_percentage(@course.progress(current_user), precision: 0)

      - @lessons.each do |lesson|
        - if @lesson.present? && lesson == @lesson
          %li.list-group-item.list-group-item-success
            = render 'lessons/lesson_preview', lesson: lesson
        - else
          %li.list-group-item
            = render 'lessons/lesson_preview', lesson: lesson